version: 0.2

phases:
  install:
   runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cat shaheryar_pre.yml
      - cat params.json
      - aws cloudformation create-stack --stack-name shaheryar-stack-task-2 --template-body file://shaheryar_pre.yml --parameters file://params.json

  post_build:
    commands:
      - echo Build completed on `date`