---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BranchName:
    Description: CodeCommit branch name
    Type: String
    Default: master
  RepositoryName:
    Description: CodeComit repository name
    Type: String
    Default: shaheryar-repo
 
Resources:
  ShaheryarCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ShaheryarCodeBuildProject
      ServiceRole: "arn:aws:iam::692560313237:role/service-role/shaheryar-codebuild-service-role-task-1"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10
      
      
  AppPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: ShaheryarCodePipeline
      RoleArn: "arn:aws:iam::692560313237:role/service-role/AWSCodePipelineServiceRole-us-east-1-shaheryar-task1-pipeline"
      Stages:
        - Name: Source
          Actions:
            - Name: CodeCommit
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceFiles
              Configuration:
                BranchName: !Ref BranchName
                RepositoryName: !Ref RepositoryName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: CodeBuild
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: SourceFiles
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: CodebuildFiles
              Configuration:
                ProjectName: ShaheryarCodeBuildProject
              RunOrder: 1
        - Name: GenerateChangeSet
          Actions:
            - Name : GenerateChangeSet
              InputArtifacts:
                - Name: CodebuildFiles
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: shaheryar-pipeline-changeset
                RoleArn: "arn:aws:iam::692560313237:role/shaheryar-cloudformation-role"
                StackName: shaheryar-stack4
                TemplateConfiguration: CodebuildFiles::conf.json
                TemplatePath: CodebuildFiles::changeset.yml
              OutputArtifacts: 
                - Name: OutputCodebuildFiles
              RunOrder: 1
        - Name: ExecuteChangeSet
          Actions:
            - Name : ExecuteChangeSet
              InputArtifacts:
                - Name: OutputCodebuildFiles
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: shaheryar-pipeline-changeset
                RoleArn: "arn:aws:iam::692560313237:role/shaheryar-cloudformation-role"
                StackName: shaheryar-stack4
              OutputArtifacts: 
                - Name: FinalOutput
              RunOrder: 2
      ArtifactStore:
         Type: S3
         Location: shaheryar-malik-devops 